import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import type { AgentConfig, Requirements, StudioApi } from './types';
import { Badge, Button, Empty, Field, Icon, Modal } from './ui';
import fixture from './data/demo-data.json';
import './config-pages.css';

type PageProps = { api: StudioApi };
const requirementFields: { key: keyof Requirements; title: string; icon: string; hint: string }[] = [
  { key: 'purpose', title: '目的 · 要解决什么问题', icon: 'flag', hint: '用一句话说明最终要交付的价值。' },
  { key: 'audience', title: '使用者 · 为谁服务', icon: 'person', hint: '具体到使用者与使用场景。' },
  { key: 'scope', title: '范围 · 负责与不负责的事', icon: 'crop_free', hint: '明确可以自主执行的范围，以及需要你介入的边界。' },
  { key: 'input', title: '输入契约', icon: 'input', hint: '写清输入来源、字段、类型、必填信息和缺失处理。' },
  { key: 'actions', title: '动作契约', icon: 'build', hint: '允许使用的工具、可读写资源与批准条件。' },
  { key: 'output', title: '输出契约', icon: 'output', hint: '交付格式、接收者、来源要求与示例。' },
  { key: 'acceptance', title: '验收条件', icon: 'task_alt', hint: '使用可验证条件，例如“每条关键事实都有支持它的证据”。' },
  { key: 'failure', title: '失败与补救', icon: 'healing', hint: '规定补查、追问、交接或终止的条件与次数。' },
];

export function RequirementsPage({ api }: PageProps) {
  const [preview, setPreview] = useState(false);
  const [createCase, setCreateCase] = useState(false);
  const [caseTitle, setCaseTitle] = useState('');
  const [caseInput, setCaseInput] = useState('');
  const [caseExpected, setCaseExpected] = useState('');
  const [caseError, setCaseError] = useState('');
  const complete = requirementFields.filter(f => api.draft.requirements[f.key].trim()).length;
  function saveCase() {
    if (!caseTitle.trim() || !caseInput.trim() || !caseExpected.trim()) { setCaseError('请补齐标题、测试输入和可验证的预期条件。'); return; }
    api.addCase({ id: `case-requirement-${Date.now()}`, title: caseTitle.trim(), layer: 'agent_task', input: { task: caseInput.trim() }, expected: caseExpected.trim() });
    setCreateCase(false); api.notify('已添加到本地回归用例；预置数据集保持不变。'); api.navigate('evals');
  }
  return <div className="config-page requirements-page">
    <div className="page-header"><div><span className="config-eyebrow">DEFINE THE OUTCOME</span><h1>要件定义</h1><p className="muted">先决定什么叫做完成，再让每一个成员围绕它工作。</p></div><Button icon="article" onClick={() => setPreview(true)}>预览任务契约</Button></div>
    <div className="requirements-layout"><div className="stack"><section className="panel requirements-name"><Field label="工作组名称"><input value={api.draft.name} aria-required="true" onChange={e => api.setDraft(d => ({ ...d, name: e.target.value }))} /></Field></section>
      <div className="requirements-grid">{requirementFields.map((f, i) => <section className="panel requirement-card" key={f.key}><div className="config-section-title"><span className="config-section-icon"><Icon name={f.icon} /></span><span className="config-step">{String(i + 1).padStart(2, '0')}</span></div><Field label={f.title} hint={f.hint}><textarea rows={f.key === 'acceptance' ? 5 : 4} value={api.draft.requirements[f.key]} aria-required={f.key === 'purpose'} placeholder="尚未定义" onChange={e => api.setDraft(d => ({ ...d, requirements: { ...d.requirements, [f.key]: e.target.value } }))} /></Field></section>)}</div>
      <div className="config-form-actions"><Button icon="fact_check" onClick={api.checkConfig}>检查配置</Button><Button variant="primary" icon="save" onClick={api.saveDraft}>保存要件草稿</Button></div>
    </div><aside className="config-aside stack"><section className="panel config-summary-panel"><div className="config-summary-head"><span className="config-summary-icon"><Icon name="visibility" size={20}/></span><div><h3>要件摘要</h3><p className="config-summary-sub">只读预览 · 根据左侧已填内容自动生成</p></div></div><div className="contract-flow"><span>输入任务</span><Icon name="arrow_downward" /><span>研究 → 核验 → 成稿</span><Icon name="arrow_downward" /><span>交付物 + 支持证据</span></div><div className="config-progress-label"><span>要件完整性</span><strong>{complete} / 8</strong></div><progress value={complete} max={8} aria-label="要件完整性" /><p className="muted">已填写不等于已通过验收。运行结果还需要用例与评价来验证。</p></section>
      <section className="panel"><h3>验收与测试</h3><p className="muted">演示模板的对应关系；改动验收条件后，请同步调整用例。</p><div className="requirement-links">{fixture.teams[0].requirements.acceptance.map(a => <button key={a.id} onClick={() => api.navigate('evals')}><Icon name="link" /><span>{a.condition}<small>{a.evaluator_version}</small></span><Icon name="chevron_right" size={18} /></button>)}</div><Button icon="add" onClick={() => { setCaseExpected(api.draft.requirements.acceptance); setCaseError(''); setCreateCase(true); }}>创建验收用例</Button></section>
    </aside></div>
    {preview && <Modal title="最终任务契约 · 当前草稿" wide onClose={() => setPreview(false)}><p className="muted">这是本地配置的预览，尚未交给模型执行。</p><div className="contract-preview">{requirementFields.map(f => <section key={f.key}><h3>{f.title}</h3><p>{api.draft.requirements[f.key] || '未定义'}</p></section>)}</div></Modal>}
    {createCase && <Modal title="从验收条件创建测试用例" onClose={() => setCreateCase(false)}><div className="stack"><Field label="用例标题"><input value={caseTitle} onChange={e => setCaseTitle(e.target.value)} /></Field><Field label="测试输入"><textarea rows={3} value={caseInput} onChange={e => setCaseInput(e.target.value)} placeholder="给智能体的具体任务" /></Field><Field label="预期条件"><textarea rows={4} value={caseExpected} onChange={e => setCaseExpected(e.target.value)} /></Field>{caseError && <p role="alert" className="config-error">{caseError}</p>}<p className="muted">新增到本地用例集合，不覆盖冻结的 dataset-v1，也不会自动执行评测。</p><div className="config-form-actions"><Button onClick={() => setCreateCase(false)}>取消</Button><Button variant="primary" onClick={saveCase}>创建用例</Button></div></div></Modal>}
  </div>;
}

const sections: { key: keyof AgentConfig; title: string; icon: string; subtitle: string }[] = [
  { key: 'input', title: '输入处理', icon: 'input', subtitle: '规范输入，明确缺失信息的处理。' },
  { key: 'guardrails', title: 'Guardrails', icon: 'shield', subtitle: '分别检查输入、工具边界与最终输出。' },
  { key: 'grounding', title: 'Grounding', icon: 'travel_explore', subtitle: '让每条主张关联到支持它的证据。' },
  { key: 'instructions', title: '指令与技能', icon: 'terminal', subtitle: '定义职责，组合可复用的任务能力。' },
  { key: 'context', title: '上下文与记忆', icon: 'memory', subtitle: '控制哪些信息可以被保留、读取和共享。' },
  { key: 'model', title: '模型', icon: 'neurology', subtitle: '按照模型能力配置推理与生成参数。' },
  { key: 'tools', title: '工具', icon: 'build', subtitle: '给工具设置权限、执行边界和失败策略。' },
  { key: 'loop', title: '执行循环', icon: 'sync', subtitle: '决定如何行动，以及何时必须结束。' },
  { key: 'output', title: '输出与补救', icon: 'fact_check', subtitle: '约束交付格式，为不合格结果安排有限的补救。' },
];
const protocols: Record<string, string> = { function: '函数调用', http_api: 'HTTP API', cli: 'CLI / 本地进程', stdio: 'MCP · stdio', streamable_http: 'MCP · Streamable HTTP' };
const toolProtocol = (t: typeof fixture.resources.tools[number]) => protocols[t.protocol === 'mcp' ? t.transport || '' : t.protocol] || t.protocol;
const sideEffects: Record<string, string> = { none: '无副作用', read: '只读资源', write_local: '写入本地文件 · 需要批准' };
const splitList = (v: string) => [...new Set(v.split(/[,，\n]/).map(x => x.trim()).filter(Boolean))];
function Options({ value, onChange, items, label }: { value: string; onChange: (v: string) => void; items: [string, string][]; label?: string }) {
  const options = items.some(([v]) => v === value) || !value ? items : [[value, value], ...items];
  return <select aria-label={label} value={value} onChange={e => onChange(e.target.value)}>{options.map(([v, title]) => <option key={v} value={v}>{title}</option>)}</select>;
}
function Check({ checked, onChange, children, hint }: { checked: boolean; onChange: (v: boolean) => void; children: ReactNode; hint?: string }) { return <label className="config-check"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><span>{children}{hint && <small>{hint}</small>}</span></label>; }
function Note({ children, warning = false }: { children: ReactNode; warning?: boolean }) { return <div className={`config-note ${warning ? 'warning' : ''}`}><Icon name={warning ? 'info' : 'lightbulb'} size={19} /><span>{children}</span></div>; }
function ListInput({ values, onChange, label, hint }: { values: string[]; onChange: (v: string[]) => void; label: string; hint?: string }) {
  const [text, setText] = useState(values.join(', '));
  const localValue = useRef(JSON.stringify(values));
  const serialized = JSON.stringify(values);
  useEffect(() => {
    if (serialized !== localValue.current) { setText(values.join(', ')); localValue.current = serialized; }
  }, [serialized, values]);
  return <Field label={label} hint={hint || '用逗号或换行分隔。'}><textarea rows={2} value={text} onChange={e => { const parsed = splitList(e.target.value); localValue.current = JSON.stringify(parsed); setText(e.target.value); onChange(parsed); }} /></Field>;
}

export function ScaffoldPage({ api }: PageProps) {
  const [section, setSection] = useState<keyof AgentConfig>('grounding');
  const [preview, setPreview] = useState(false);
  const [newField, setNewField] = useState(false);
  const [fieldName, setFieldName] = useState('');
  const [fieldType, setFieldType] = useState('string');
  const [fieldError, setFieldError] = useState('');
  const members = api.draft.nodes.filter(n => n.agent_id && api.draft.configs[n.agent_id]);
  const member = members.find(n => n.id === api.selectedNode) || members[0];
  if (!member?.agent_id) return <div className="config-page"><Empty title="还没有可配置的成员">在画布中添加智能体节点，再为它设置脚手架。</Empty><Button onClick={() => api.navigate('canvas')}>返回编排画布</Button></div>;
  const agentId = member.agent_id;
  const config = api.draft.configs[agentId];
  const active = sections.find(s => s.key === section)!;
  const model = fixture.resources.models.find(m => m.id === config.model.model_id);
  function update<K extends keyof AgentConfig>(key: K, patch: Partial<AgentConfig[K]>) {
    api.setDraft(d => ({ ...d, configs: { ...d.configs, [agentId]: { ...d.configs[agentId], [key]: { ...d.configs[agentId][key], ...patch } } } }));
  }
  function changeModel(id: string) {
    const m = fixture.resources.models.find(x => x.id === id)!;
    update('model', { model_id: id, provider_id: m.provider_id, reasoning_effort: m.capabilities.reasoning_efforts.includes(config.model.reasoning_effort || '') ? config.model.reasoning_effort : m.capabilities.reasoning_efforts[0] || null, temperature: m.capabilities.temperature ? 0.4 : null, fallback_model_id: config.model.fallback_model_id === id ? null : config.model.fallback_model_id, unsupported_parameters: m.capabilities.temperature ? ['reasoning_effort'] : ['temperature'], connection_status: 'unconnected' });
  }
  function addField() {
    const name = fieldName.trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) { setFieldError('字段名使用字母、数字和下划线，不能以数字开头。'); return; }
    if (name in config.input.fields) { setFieldError('这个字段已经存在。'); return; }
    update('input', { fields: { ...config.input.fields, [name]: fieldType } }); setNewField(false);
  }
  function removeField(name: string) {
    const fields = { ...config.input.fields }; delete fields[name as keyof typeof fields];
    update('input', { fields, required_fields: config.input.required_fields.filter(n => n !== name) });
  }
  const effectivePrompt = `${config.instructions.system}\n\n任务模板\n${config.instructions.task_template}\n\n启用技能\n${config.instructions.skill_ids.map(id => fixture.resources.skills.find(s => s.id === id)?.content || id).join('\n') || '无'}\n\n输出要求\n格式：${config.output.format}\n字段：${config.output.fields.join(', ')}\n证据不足：${config.grounding.on_insufficient_evidence}`;
  let content: ReactNode;
  switch (section) {
    case 'input': content = <><div className="config-inline-header"><h3>输入字段</h3><Button icon="add" onClick={() => { setFieldName(''); setFieldType('string'); setFieldError(''); setNewField(true); }}>添加字段</Button></div><div className="input-schema"><div className="input-schema-header"><span>字段名</span><span>类型</span><span>必填</span><span /></div>{Object.entries(config.input.fields).filter(([, type]) => type).map(([name, type]) => <div className="input-schema-row" key={name}><code>{name}</code><Options label={`${name} 字段类型`} value={type || 'string'} onChange={v => update('input', { fields: { ...config.input.fields, [name]: v } })} items={['string', 'array', 'object', 'number', 'boolean'].map(v => [v, v])} /><input aria-label={`${name} 必填`} type="checkbox" checked={config.input.required_fields.includes(name)} onChange={e => update('input', { required_fields: e.target.checked ? [...config.input.required_fields, name] : config.input.required_fields.filter(f => f !== name) })} /><button className="icon-button" aria-label={`删除 ${name} 字段`} onClick={() => removeField(name)}><Icon name="close" size={18} /></button></div>)}</div><div><h3>标准化与附件处理</h3>{[['trim_text', '清理首尾空白'], ['parse_attachments', '解析附件'], ['normalize_encoding', '统一文本编码']].map(([id, label]) => <Check key={id} checked={config.input.normalization.includes(id)} onChange={v => update('input', { normalization: v ? [...config.input.normalization, id] : config.input.normalization.filter(x => x !== id) })}>{label}</Check>)}</div><Field label="缺少必填信息时"><Options value={config.input.missing_fields} onChange={v => update('input', { missing_fields: v })} items={[[ 'ask_user', '向用户追问'], ['reject', '阻断并说明缺失字段'], ['use_defined_default', '使用契约明确规定的默认值']]} /></Field><Note>这里编辑输入契约。模拟运行只处理本地文本与案例，没有附件解析服务。</Note></>; break;
    case 'guardrails': content = <>{([['input', '输入检查', '模型接收任务之前'], ['tool_arguments', '工具参数检查', '工具执行之前'], ['tool_results', '工具结果检查', '工具结果进入上下文之前'], ['output', '输出检查', '交付给用户之前']] as const).map(([key, label, hint]) => <Field key={key} label={label} hint={hint}><Options value={config.guardrails[key]} onChange={v => update('guardrails', { [key]: v })} items={[[ 'schema_check', '字段与结构校验'], ['read_only_scope', '资源权限与只读范围'], ['untrusted_evidence', '将外部内容视为未验证证据'], ['claim_evidence_mapping', '逐条核对主张与证据'], ['evidence_and_schema', '证据充分性 + 结构校验'], ['disabled', '暂不检查']]} /></Field>)}<Field label="检查失败时"><Options value={config.guardrails.on_failure} onChange={v => update('guardrails', { on_failure: v })} items={[[ 'flag_and_continue', '标记问题并继续'], ['supplement_once', '补查一次并重新核验'], ['block', '阻断执行'], ['human_review', '转人工确认']]} /></Field><Note warning>每个边界独立检查。入口检查不会自动保护后续的工具调用和成员交接。</Note></>; break;
    case 'grounding': content = <><div><h3>知识源</h3>{fixture.resources.knowledge.map(k => <Check key={k.id} checked={config.grounding.source_ids.includes(k.id)} onChange={v => update('grounding', { source_ids: v ? [...config.grounding.source_ids, k.id] : config.grounding.source_ids.filter(id => id !== k.id) })} hint={`${k.id} · 未接入 · 示例目录`}>{k.name}</Check>)}</div><div className="two-columns"><Field label="检索方式"><Options value={config.grounding.retrieval} onChange={v => update('grounding', { retrieval: v })} items={[[ 'mock_keyword_vector', '关键词 + 向量（模拟）'], ['mock_keyword', '关键词（模拟）'], ['provided_evidence_only', '仅使用上游证据']]} /></Field><Field label="重排策略"><Options value={config.grounding.rerank} onChange={v => update('grounding', { rerank: v })} items={[[ 'mock_reranker', '相关性重排（模拟）'], ['none', '保留检索顺序']]} /></Field></div><Field label="证据时效（天）" hint="0 表示只接受当天的证据；这里只保存策略。"><input type="number" min="0" value={config.grounding.freshness_days} onChange={e => update('grounding', { freshness_days: Math.max(0, Number(e.target.value)) })} /></Field><Check checked={config.grounding.require_citations} onChange={v => update('grounding', { require_citations: v })} hint="主张逐条绑定支持它的来源；只有引用数量不能证明结论。">要求引用支持关键事实</Check><Field label="证据不足时"><Options value={config.grounding.on_insufficient_evidence} onChange={v => update('grounding', { on_insufficient_evidence: v })} items={[[ 'flag_and_continue', '标记不足，继续执行'], ['supplement_once_then_escalate', '补查一次，仍不足则转人工'], ['retrieve_more', '在预算内继续补查'], ['ask_user', '请求用户补充来源'], ['stop', '终止并报告无法判定']]} /></Field><Note>知识库与检索服务尚未接入。改变策略会保存到草稿，并被后续模拟运行的配置快照记录。</Note></>; break;
    case 'instructions': content = <><Field label="系统指令" hint="明确职责、决策边界和输出要求。"><textarea rows={6} value={config.instructions.system} onChange={e => update('instructions', { system: e.target.value })} /></Field><Field label="任务模板" hint="使用 {{task}} 引用任务内容。"><textarea rows={3} value={config.instructions.task_template} onChange={e => update('instructions', { task_template: e.target.value })} /></Field><div><h3>可复用技能</h3>{fixture.resources.skills.map(skill => <Check key={skill.id} checked={config.instructions.skill_ids.includes(skill.id)} onChange={v => update('instructions', { skill_ids: v ? [...config.instructions.skill_ids, skill.id] : config.instructions.skill_ids.filter(id => id !== skill.id) })} hint={`v${skill.version} · ${skill.content}`}>{skill.label}</Check>)}</div><Button icon="terminal" onClick={() => setPreview(true)}>预览最终生效指令</Button></>; break;
    case 'context': content = <><Field label="会话历史范围"><Options value={config.context.history} onChange={v => update('context', { history: v })} items={[[ 'current_run', '仅当前运行'], ['current_session', '当前会话'], ['none', '不携带历史']]} /></Field><div className="two-columns"><Field label="上下文预算（Token）"><input type="number" min="256" step="256" value={config.context.budget_tokens} onChange={e => update('context', { budget_tokens: Math.max(256, Number(e.target.value)) })} /></Field><Field label="压缩策略"><Options value={config.context.compression} onChange={v => update('context', { compression: v })} items={[[ 'summarize_completed_steps', '压缩已完成步骤'], ['trim_oldest', '移除最早上下文'], ['none', '不压缩；超限时停止']]} /></Field></div><Field label="成员私有记忆"><Options value={config.context.private_memory} onChange={v => update('context', { private_memory: v })} items={[[ 'read_only_mock', '只读（模拟）'], ['read_write_mock', '可读写（模拟）'], ['disabled', '禁用']]} /></Field><Field label="团队共享记忆"><Options value={config.context.shared_memory} onChange={v => update('context', { shared_memory: v })} items={[[ 'team_evidence_board', '团队证据板'], ['disabled', '禁用']]} /></Field><div><h3>允许写入共享区域</h3>{[['evidence', '证据'], ['gaps', '待补查缺口'], ['verification', '核验结果'], ['report', '报告草稿']].map(([id, label]) => <Check key={id} checked={config.context.shared_write_scope.includes(id)} onChange={v => update('context', { shared_write_scope: v ? [...config.context.shared_write_scope, id] : config.context.shared_write_scope.filter(x => x !== id) })}>{label}</Check>)}</div><Note>记忆策略可以配置；持久记忆服务尚未接入。浏览器保存的是工作台配置。</Note></>; break;
    case 'model': content = <><div className="config-model-header"><span className="config-section-icon"><Icon name="neurology" size={28} /></span><div><strong>演示模型提供方</strong><small>provider-mock · 能力来自本地目录</small></div><Badge>未接入</Badge></div><Field label="模型 / 版本"><Options value={config.model.model_id} onChange={changeModel} items={fixture.resources.models.map(m => [m.id, `${m.label} · ${m.id}`])} /></Field>{model?.capabilities.reasoning_efforts.length ? <Field label="推理强度" hint="使用模型提供的能力选项；不会展示隐藏思维链。"><Options value={config.model.reasoning_effort || ''} onChange={v => update('model', { reasoning_effort: v })} items={model.capabilities.reasoning_efforts.map(v => [v, ({ low: '低 · low', medium: '中 · medium', high: '高 · high' } as Record<string, string>)[v] || v])} /></Field> : model ? <Note>这个模拟模型不提供推理强度参数。</Note> : <Note warning>模型不在能力目录中，参数支持情况未验证。请选择目录中的模拟模型。</Note>}{model?.capabilities.temperature ? <Field label="Temperature" hint="0 更稳定，较高值允许更多表达变化。模拟目录支持范围 0–2。"><input type="number" min="0" max="2" step="0.1" value={config.model.temperature ?? 0.4} onChange={e => update('model', { temperature: Math.max(0, Math.min(2, Number(e.target.value))) })} /></Field> : model && <Note>这个模拟模型不支持 temperature；切换模型时会自动清除不兼容参数。</Note>}<div className="two-columns"><Field label="最大输出 Token"><input type="number" min="1" step="128" value={config.model.max_output_tokens} onChange={e => update('model', { max_output_tokens: Math.max(1, Number(e.target.value)) })} /></Field><Field label="单次请求超时（秒）"><input type="number" min="1" value={config.model.timeout_seconds} onChange={e => update('model', { timeout_seconds: Math.max(1, Number(e.target.value)) })} /></Field></div><Field label="备用模型"><Options value={config.model.fallback_model_id || ''} onChange={v => update('model', { fallback_model_id: v || null })} items={[[ '', '不使用备用模型'], ...fixture.resources.models.filter(m => m.id !== config.model.model_id).map(m => [m.id, m.label] as [string, string])]} /></Field><Note warning>这里不会调用模型，也不接收 API Key。接入真实提供方后，需要重新发现和验证模型能力。</Note></>; break;
    case 'tools': content = <><p className="muted">勾选成员允许引用的工具。工具目录均未接入；选择它不会建立连接。</p><div className="config-tool-list">{fixture.resources.tools.map(t => <div className="config-tool" key={t.id}><Check checked={config.tools.allowed_ids.includes(t.id)} onChange={v => update('tools', { allowed_ids: v ? [...config.tools.allowed_ids, t.id] : config.tools.allowed_ids.filter(id => id !== t.id) })} hint={`${toolProtocol(t)} · ${sideEffects[t.side_effect]}`}>{t.label}</Check><details><summary>协议与结构详情</summary><dl><dt>传输 / 协议</dt><dd>{toolProtocol(t)}</dd><dt>权限与副作用</dt><dd>{sideEffects[t.side_effect]}</dd><dt>认证引用</dt><dd>未配置</dd><dt>输入</dt><dd><code>query: string</code>（必填）</dd><dt>输出</dt><dd><code>result: array</code>（必填）</dd><dt>状态</dt><dd>未接入 · 仅模拟数据</dd></dl></details></div>)}</div><div className="two-columns"><Field label="默认工具超时（秒）"><input type="number" min="1" value={config.tools.default_timeout_seconds} onChange={e => update('tools', { default_timeout_seconds: Math.max(1, Number(e.target.value)) })} /></Field><Field label="失败重试次数"><input type="number" min="0" max="10" value={config.tools.retry_count} onChange={e => update('tools', { retry_count: Math.max(0, Math.min(10, Number(e.target.value))) })} /></Field></div><Field label="批准规则"><Options value={config.tools.approval} onChange={v => update('tools', { approval: v })} items={[[ 'required_before_external_write', '所有外部写操作先批准'], ['required_before_any_write', '任何写操作先批准'], ['always', '每次工具调用先批准']]} /></Field><Note warning>工具目录的本地写入批准要求始终保留。当前 Web 版不启动 CLI、MCP 或 HTTP 工具。</Note></>; break;
    case 'loop': content = <><Field label="执行策略"><Options value={config.loop.strategy} onChange={v => update('loop', { strategy: v })} items={[[ 'direct', '直接回答'], ['ReAct', 'ReAct · 动作与观察循环'], ['plan_then_execute', '规划后执行']]} /></Field><Field label="继续条件"><input value={config.loop.continue_when} onChange={e => update('loop', { continue_when: e.target.value })} /></Field><Field label="终止条件" hint="必须可判断，避免成员之间无限退回。"><input value={config.loop.stop_when} onChange={e => update('loop', { stop_when: e.target.value })} /></Field><div className="two-columns"><Field label="成员最大步骤"><input type="number" min="1" max="100" value={config.loop.max_steps} onChange={e => update('loop', { max_steps: Math.max(1, Number(e.target.value)) })} /></Field><Field label="连续无进展上限"><input type="number" min="1" value={config.loop.no_progress_limit} onChange={e => update('loop', { no_progress_limit: Math.max(1, Number(e.target.value)) })} /></Field><Field label="成员总时限（秒）"><input type="number" min="1" value={config.loop.timeout_seconds} onChange={e => update('loop', { timeout_seconds: Math.max(1, Number(e.target.value)) })} /></Field><Field label="成员费用上限（USD）"><input type="number" min="0" step="0.01" value={config.loop.cost_limit_usd} onChange={e => update('loop', { cost_limit_usd: Math.max(0, Number(e.target.value)) })} /></Field></div><div className="config-team-budget"><Icon name="groups" /><div><strong>团队上限单独生效</strong><p>最多退回 {api.draft.budget.maxReturns} 次 · 总时限 {api.draft.budget.maxSeconds}s · 总费用 ${api.draft.budget.maxCost.toFixed(2)}</p></div><Button onClick={() => api.navigate('canvas')}>团队配置</Button></div><Note>ReAct 记录可观察的动作、工具结果与决策摘要，不展示模型的隐藏思维链。所有执行仍为模拟。</Note></>; break;
    case 'output': content = <><Field label="交付格式"><Options value={config.output.format} onChange={v => update('output', { format: v })} items={[[ 'json', '结构化 JSON'], ['markdown', 'Markdown 文本'], ['text', '纯文本'], ['file', '文件（接口预留）']]} /></Field><ListInput label="输出字段" values={config.output.fields} onChange={v => update('output', { fields: v })} /><Check checked={config.output.schema_validation} onChange={v => update('output', { schema_validation: v })}>检查输出字段与结构</Check><Field label="内容校验规则"><Options value={config.output.content_validation} onChange={v => update('output', { content_validation: v })} items={fixture.evaluator_versions.map(e => [e.id, `${e.label} · ${e.id}`])} /></Field><Field label="校验失败后的补救"><Options value={config.output.repair_action} onChange={v => update('output', { repair_action: v })} items={[[ 'retrieve_more', '补查证据'], ['regenerate', '重新生成'], ['return_to_researcher', '退回研究员'], ['ask_user', '向用户追问'], ['human_review', '转人工处理']]} /></Field><div className="two-columns"><Field label="最多补救次数"><input type="number" min="0" max="10" value={config.output.repair_limit} onChange={e => update('output', { repair_limit: Math.max(0, Math.min(10, Number(e.target.value))) })} /></Field><Field label="补救耗尽时"><Options value={config.output.on_exhausted} onChange={v => update('output', { on_exhausted: v })} items={[[ 'human_review', '转人工并保留证据'], ['stop_with_partial_result', '停止并返回部分结果'], ['report_blocked', '报告无法完成']]} /></Field></div><Note>“执行完成”和“质量合格”分别记录。输出缺少证据时，不能仅因为成功生成文本就判为通过。</Note></>; break;
  }
  return <div className="config-page scaffold-page"><div className="page-header"><div><span className="config-eyebrow">AGENT SCAFFOLD</span><h1>{member.label} · 成员脚手架</h1><p className="muted">当前编辑独立草稿，历史版本和运行快照保持不变。</p></div><Button icon="arrow_back" onClick={() => api.navigate('canvas')}>返回画布</Button></div><div className="scaffold-member-row"><span>配置成员</span><div role="group" aria-label="选择配置成员">{members.map(m => <button className={m.id === member.id ? 'selected' : ''} key={m.id} onClick={() => api.selectNode(m.id)}><Icon name={m.agent_id?.includes('verifier') ? 'fact_check' : m.agent_id?.includes('writer') ? 'edit_note' : 'search'} size={18} />{m.label}</button>)}</div><Badge>草稿</Badge></div>
    <div className="scaffold-layout"><nav className="scaffold-sections" aria-label="脚手架配置分类">{sections.map(s => <button key={s.key} className={section === s.key ? 'active' : ''} onClick={() => setSection(s.key)} aria-current={section === s.key ? 'page' : undefined}><Icon name={s.icon} size={20} /><span>{s.title}</span></button>)}</nav><section className="panel scaffold-main"><div className="config-editor-title"><h2>{active.title}</h2><p className="muted">{active.subtitle}</p></div><div className="config-editor-fields">{content}</div><div className="config-form-actions"><Button icon="terminal" onClick={() => setPreview(true)}>预览最终指令</Button><Button variant="primary" icon="save" onClick={api.saveDraft}>保存成员配置</Button></div></section><aside className="config-aside stack"><section className="panel"><h3>配置摘要</h3><Badge>模拟配置 · 未接入</Badge><dl className="config-summary"><dt>模型</dt><dd>{config.model.model_id}</dd><dt>推理 / 采样</dt><dd>{config.model.reasoning_effort ? `推理强度 ${config.model.reasoning_effort}` : `Temperature ${config.model.temperature ?? '未设置'}`}</dd><dt>允许工具</dt><dd>{config.tools.allowed_ids.length ? config.tools.allowed_ids.map(id => fixture.resources.tools.find(t => t.id === id)?.label || id).join(' / ') : '没有工具权限'}</dd><dt>循环策略</dt><dd>{config.loop.strategy} · 最多 {config.loop.max_steps} 步</dd><dt>输出字段</dt><dd>{config.output.fields.join(' / ') || '未定义'}</dd></dl></section><section className="panel"><h3>修改之后</h3><p className="muted">用相同测试检查改动。保存配置不会自动运行或改变默认版本。</p><div className="config-next-actions"><Button icon="fact_check" onClick={api.checkConfig}>检查配置</Button><Button icon="science" onClick={() => api.navigate('playground')}>前往模拟试运行</Button><Button icon="compare_arrows" onClick={() => api.navigate('compare')}>版本比较</Button></div></section></aside></div>
    {preview && <Modal title={`${member.label} · 最终指令预览`} wide onClose={() => setPreview(false)}><p className="muted">由当前草稿的系统指令、技能与输出规则组成；未发送给模型。</p><pre className="config-prompt-preview">{effectivePrompt}</pre></Modal>}
    {newField && <Modal title="添加输入字段" onClose={() => setNewField(false)}><div className="stack"><Field label="字段名"><input value={fieldName} onChange={e => setFieldName(e.target.value)} placeholder="例如 source_url" /></Field><Field label="字段类型"><Options value={fieldType} onChange={setFieldType} items={['string', 'array', 'object', 'number', 'boolean'].map(v => [v, v])} /></Field>{fieldError && <p role="alert" className="config-error">{fieldError}</p>}<div className="config-form-actions"><Button onClick={() => setNewField(false)}>取消</Button><Button variant="primary" onClick={addField}>添加字段</Button></div></div></Modal>}
  </div>;
}

type CatalogResource = { id: string; name: string; kind: string; icon: string; summary: string; state: string; details: ReactNode };
export function ResourcesPage({ api }: PageProps) {
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState('tool-search-http');
  const catalog: CatalogResource[] = [
    ...fixture.resources.tools.map(t => ({ id: t.id, name: t.label, kind: 'tools', icon: 'build', summary: `${toolProtocol(t)} · ${sideEffects[t.side_effect]}`, state: '未接入', details: <><dl className="resource-detail-list"><dt>协议与传输</dt><dd>{toolProtocol(t)}</dd><dt>资源权限 / 副作用</dt><dd>{sideEffects[t.side_effect]}</dd><dt>批准要求</dt><dd>{t.approval_required ? '执行前必须批准' : '遵循成员批准规则'}</dd><dt>默认超时 / 重试</dt><dd>{t.timeout_seconds}s / {t.retries} 次</dd><dt>认证引用 / 地址</dt><dd>尚未配置</dd></dl><h3>输入结构</h3><pre>{JSON.stringify(t.input_schema, null, 2)}</pre><h3>输出结构</h3><pre>{JSON.stringify(t.output_schema, null, 2)}</pre></> })),
    ...fixture.resources.models.map(m => ({ id: m.id, name: m.label, kind: 'models', icon: 'neurology', summary: m.capabilities.reasoning_efforts.length ? `推理强度 ${m.capabilities.reasoning_efforts.join(' / ')}` : '支持 Temperature · 无推理强度参数', state: '未接入', details: <><dl className="resource-detail-list"><dt>提供方</dt><dd>{m.provider_id}</dd><dt>推理能力</dt><dd>{m.capabilities.reasoning_efforts.join(' / ') || '不支持推理参数'}</dd><dt>Temperature</dt><dd>{m.capabilities.temperature ? '支持（模拟能力目录）' : '不支持'}</dd><dt>能力来源</dt><dd>本地模拟目录，未实时发现</dd></dl><Note>实际模型接入后需重新验证参数支持情况。</Note></> })),
    ...fixture.resources.knowledge.map(k => ({ id: k.id, name: k.name, kind: 'knowledge', icon: 'menu_book', summary: `${k.document_count} 份示例文档 · 仅模拟目录`, state: '未接入', details: <><p>此知识源用于表达研究、检索和来源核验的配置关系。</p><dl className="resource-detail-list"><dt>文档数</dt><dd>{k.document_count}（模拟数据）</dd><dt>更新状态</dt><dd>未采集</dd><dt>检索服务</dt><dd>未接入</dd></dl></> })),
    ...fixture.resources.skills.map(s => ({ id: s.id, name: s.label, kind: 'skills', icon: 'terminal', summary: `v${s.version} · 可复用指令`, state: '本地定义', details: <><Badge>版本 {s.version}</Badge><h3>技能内容</h3><p>{s.content}</p><Note>这段指令可被成员引用；保存定义不代表执行过技能。</Note></> })),
    ...fixture.evaluator_versions.map(e => ({ id: e.id, name: e.label, kind: 'evaluators', icon: 'fact_check', summary: `${e.kind === 'code' ? 'Code-as-a-Judge' : e.kind === 'llm' ? 'LLM-as-a-Judge' : '人工评价'} · 固定版本`, state: e.kind === 'human' ? '本地评价' : '未接入', details: <><dl className="resource-detail-list"><dt>类型</dt><dd>{e.kind}</dd><dt>模型</dt><dd>{e.model_id || '不使用模型'}</dd><dt>规则版本</dt><dd>{e.code_version || e.id}</dd></dl><h3>判定依据</h3><p>{e.rule || e.criteria || Object.entries(e.rubric || {}).map(([k, v]) => `${k}: ${v}`).join('；')}</p><Note>评估器与运行中的核验员是不同角色。演示结果不能替代实际评测。</Note></> })),
    ...fixture.resources.connectors.map(c => ({ id: c.id, name: c.label, kind: 'connectors', icon: 'hub', summary: ({ model_provider: '模型连接器', trace_exporter: '追踪导出', test_runner: '测试执行器' } as Record<string, string>)[c.kind], state: '未接入', details: <><p>这里预留 {c.label} 的接入位置。当前没有连接服务或保存凭证。</p><dl className="resource-detail-list"><dt>适配器状态</dt><dd>未实现</dd><dt>凭证引用</dt><dd>未配置</dd></dl>{c.id === 'otel-collector' && <Note>当前 Trace 是 OpenTelemetry 风格的本地域模型，不是可发送给 Collector 的 OTLP 数据包。</Note>}<Note warning>前端按钮不会伪造服务已连接。后续需要实现执行引擎与适配器。</Note></> })),
  ];
  const items = catalog.filter(r => (filter === 'all' || r.kind === filter) && `${r.name} ${r.id} ${r.summary}`.toLowerCase().includes(search.toLowerCase()));
  const current = items.find(r => r.id === selected) || items[0];
  const categories = [['all', '全部'], ['tools', '工具'], ['models', '模型'], ['knowledge', '知识源'], ['skills', '技能'], ['evaluators', '评估器'], ['connectors', '连接器']];
  return <div className="config-page resources-page"><div className="page-header"><div><span className="config-eyebrow">REUSABLE BUILDING BLOCKS</span><h1>资源库</h1><p className="muted">统一查看成员可引用的能力、协议与权限边界。</p></div><Badge>本地目录 · 执行连接未接入</Badge></div><div className="resource-toolbar"><div className="resource-filters" role="group" aria-label="资源类型">{categories.map(([id, label]) => <button className={filter === id ? 'active' : ''} key={id} onClick={() => setFilter(id)}>{label}<span>{id === 'all' ? catalog.length : catalog.filter(r => r.kind === id).length}</span></button>)}</div><label className="resource-search"><Icon name="search" /><input placeholder="搜索资源或协议" aria-label="搜索资源或协议" value={search} onChange={e => setSearch(e.target.value)} /></label></div>
    <div className="resources-layout"><div className="resource-grid">{items.map(r => <button className={`resource-card ${r.id === current?.id ? 'active' : ''}`} key={r.id} onClick={() => setSelected(r.id)}><div className="resource-card-top"><span className="config-section-icon"><Icon name={r.icon} size={23} /></span><Badge>{r.state}</Badge></div><h3>{r.name}</h3><p>{r.summary}</p><small>{r.id}</small><span className="resource-card-foot">查看详情<Icon name="arrow_forward" size={17} /></span></button>)}{!items.length && <Empty icon="search_off" title="没有匹配的资源">换一个名称、协议或资源类型试试。</Empty>}</div>{current && <aside className="panel resource-detail"><div className="resource-detail-head"><span className="config-section-icon"><Icon name={current.icon} size={28} /></span><Badge>{current.state}</Badge></div><h2>{current.name}</h2><code className="resource-id">{current.id}</code><div className="resource-detail-body">{current.details}</div><Button icon="tune" onClick={() => { if (current.kind === 'evaluators') api.navigate('evals'); else if (current.kind === 'connectors') api.notify('接入能力尚未实现；当前仅管理本地配置与模拟记录。'); else api.navigate('scaffold'); }}>{current.kind === 'evaluators' ? '查看测试评估' : current.kind === 'connectors' ? '查看接入状态' : '在成员配置中引用'}</Button></aside>}</div>
  </div>;
}
